### ISSUE TITLE
SmartOS cannot build on master

### ISSUE THREAD

**Issue by targos** [nodejs/v8#1]
It seems that `std::to_string` does not exist on this platform ?

I tried to change the `std` flag to `gnu++11` but get the same error:

```
g++ '-DV8_TARGET_ARCH_IA32' '-D__C99FEATURES__=1' '-DENABLE_DISASSEMBLER' '-DV8_I18N_SUPPORT' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' '-DUCONFIG_NO_LEGACY_CONVERSION=1' '-DUCONFIG_NO_CONVERSION=1' -I../deps/v8 -I../. -I/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos14-32/out/Release/obj/gen -I../deps/v8/include -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common  -Wall -Wextra -Wno-unused-parameter -m32 -pthreads -msse2 -mfpmath=sse -mmmx -fno-strict-aliasing -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++11 -MMD -MF /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos14-32/out/Release/.deps//home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos14-32/out/Release/obj.target/v8_base/deps/v8/src/parsing/preparse-data.o.d.raw   -c -o /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos14-32/out/Release/obj.target/v8_base/deps/v8/src/parsing/preparse-data.o ../deps/v8/src/parsing/preparse-data.cc
In file included from ../deps/v8/src/ast/modules.h:8:0,
                 from ../deps/v8/src/ast/ast.h:10,
                 from ../deps/v8/src/parsing/parser.h:8,
                 from ../deps/v8/src/parsing/parser.cc:5:
../deps/v8/src/parsing/scanner.h: In member function 'void v8::internal::Scanner::LiteralBuffer::AddChar(v8::internal::uc32)':
../deps/v8/src/parsing/scanner.h:372:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (code_unit <= unibrow::Latin1::kMaxChar) {
                                           ^
../deps/v8/src/parsing/scanner.h:379:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (code_unit <= unibrow::Utf16::kMaxNonSurrogateCharCode) {
                                        ^
../deps/v8/src/parsing/parser.cc: In function 'const v8::internal::AstRawString* v8::internal::ClassFieldVariableName(bool, v8::internal::AstValueFactory*, int)':
../deps/v8/src/parsing/parser.cc:3360:25: error: 'to_string' is not a member of 'std'
       ".class-field-" + std::to_string(index) + (is_name ? "-name" : "-func");
                         ^
deps/v8/src/v8_base.target.mk:587: recipe for target '/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos14-32/out/Release/obj.target/v8_base/deps/v8/src/parsing/parser.o' failed
```

Build: https://ci.nodejs.org/job/node-test-commit-smartos/4536/nodes=smartos14-32/console
/cc @nodejs/platform-solaris

**Comment by misterdjules** [comment]
Looking at it.

**Comment by misterdjules** [comment]
This is related to https://github.com/joyent/pkgsrc/issues/270. TL;DR: using a SmartOS VM that uses a 15.4 SmartOS image allows to build this branch successfully.

I'd still like to make sure that the changes that were made to GCC in 15.x SmartOS images allow to generate a binary that is backward compatible to run on 14.4 images. But in the meantime, using a SmartOS VM with a 15.4 image will allow you to move forward.

Please don't hesitate to let me know if you have any other question or problem with SmartOS builds!

**Comment by misterdjules** [comment]
I just realized that you might need help from the @nodejs/build team to make sure the relevant Jenkins jobs run on SmartOS VMs that use a 15.4 image.

**Comment by jbergstroem** [comment]
@misterdjules are you saying we should drop smartos14 for v7 and forward?

**Comment by jbergstroem** [comment]
We're currently building 0.10/0.12 releases with smartos13 and (up to now) everything else with smartos14.

**Comment by targos** [comment]
@jbergstroem perhaps we could start by adding a SmartOS 15.x image to the `node-test-commit-smartos` job ?

**Comment by jbergstroem** [comment]
@targos we don't have one running (yet). This is worrisome seeing how we treat smartos15+ as experimental in the upcoming supported platforms list.

I've [reached out to others](https://github.com/nodejs/build/issues/492#issuecomment-250349553) (in or outside of the build group) to help out imaging the vm. Hopefully the smartos14 playbook should just work.

**Comment by misterdjules** [comment]
> @misterdjules are you saying we should drop smartos14 for v7 and forward?

I'm not saying that, what I'm saying is that currently, no compiler available on SmartOS 14.x images can build the `v8-5.5` branch. After these changes land in master, we'll have two options:
1. building master (and releases based off of the commit that merges these changes or later commits) with the compiler available on 15.4 images.
2. building master (and releases based off of the commit that merges these changes or later commits) with a new compiler that would be based on the current 14.4 compilers + backports of fixes made to compilers available on 15.4 images.

With option 1), I'm not sure we can be 100% certain that node binaries would run on SmartOS images < 15.4. For that I need to check with the team building the compiler packages to determine if these compilers are ABI backward-compatible with the compilers available on 14.4 images. I would think that they're not, but I don't build these packages, so I'd rather ask.

As for option 2), I'm not sure if that's feasible, because I don't build these packages.

I was also saying that while we figure out which option we want to go to, anyone willing to work on the `v8-5.5` branch can build SmartOS binaries using compilers found in 15.4 images.

I'll keep you posted asap.

**Comment by misterdjules** [comment]
> @jbergstroem perhaps we could start by adding a SmartOS 15.x image to the node-test-commit-smartos job ?
> 
> > @targos we don't have one running (yet).

Don't we have the `test-joyent-smartos15-x64-1` and  `test-joyent-smartos15-x64-2` nodes connected to Jenkins and labelled `smartos15-64`?  Or am I missing something?

**Comment by misterdjules** [comment]
> I'll keep you posted asap.

I got confirmation that there is no guarantee that binaries built on 15.x images will _always_ run on 14.x images, and back porting compiler fixes to 14.4 images is currently not an option.

What that means is that SmartOS binaries for node versions that include v8 5.5 will need to be built on 15.4 images, and will be guaranteed to work only on 15.4 images and later. SmartOS users who will need to run these binaries will need to upgrade to 15.4 images or later.

**Comment by targos** [comment]
Does it mean that an update to V8 5.5 would be semver-major ? If that's the case, we may want to float a patch to replace the use of `std::to_string` by something else.

**Comment by misterdjules** [comment]
> Does it mean that an update to V8 5.5 would be semver-major ? 

I don't think so. The problem on SmartOS is due to a bug in SmartOS packages, and if SmartOS packagers thought requiring 15.4 images for node versions that ship with V8 5.5 was unreasonable, then they could patch the compilers shipping with 14.4 images.

**Comment by misterdjules** [comment]
> Does it mean that an update to V8 5.5 would be semver-major ?
> 
> > I don't think so. 

Or rather: the reason to have the update to v8 5.5 be semver-major shouldn't be the new requirement for SmartOS builds. However, wouldn't an upgrade to v8 5.5 be semver-major anyway? Or are the changes between V8 5.4 and V8 5.5 ABI compatible?

**Comment by jbergstroem** [comment]
@misterdjules I added the slaves but the playbooks had to be verified. I spent a few hours working on it today and we have a first run through both 15 and 16 here: https://ci.nodejs.org/job/node-test-commit-smartos/4584/

**Comment by jbergstroem** [comment]
(apologies; I didn't realise this was v8 5.5)

**Comment by targos** [comment]
Here's a successful (minus flaky test) CI run on SmartOS 15 and 16: https://ci.nodejs.org/job/node-test-commit-smartos/4623/

@misterdjules @jbergstroem thanks a lot for your time!

**Comment by jbergstroem** [comment]
Should we skip 14 on master then?

**Comment by misterdjules** [comment]
Yes, I think we will have to not build master on 14.x images. If that turns out to be a problem for users of 14.x images, then we can reevaluate.

**Comment by targos** [comment]
Wouldn't it be in contradiction with the list of supported platforms (https://github.com/nodejs/node/pull/8922) ?

**Comment by jbergstroem** [comment]
@targos not sure what you mean? we already do smartos releases but call them sunos.

**Comment by targos** [comment]
![image](https://cloud.githubusercontent.com/assets/2352663/19190396/9bac799a-8c9d-11e6-9949-15f57f28ca96.png)

SmartOS 14 is in tier 2.

**Comment by jbergstroem** [comment]
Oh, sorry -- yeah; that will have to be fixed for 7.x. The current list reflects 6.x. Once we land it we'll PR against other branches (4.x also needs to be taken into regard).

**Comment by misterdjules** [comment]
Thank you @jbergstroem for taking care of this, it is very much appreciated!
