### ISSUE TITLE
Build failure on Ubuntu 12.04 with 5.7-lkgr

### ISSUE THREAD

**Issue by targos** [nodejs/v8#5]
CI run: https://ci.nodejs.org/job/node-test-commit-linux/8035/

Error:
```
In file included from ../deps/v8/src/debug/debug.h:23:0,
                 from ../deps/v8/src/x64/assembler-x64-inl.h:11,
                 from ../deps/v8/src/assembler-inl.h:13,
                 from ../deps/v8/src/macro-assembler.h:8,
                 from ../deps/v8/src/deoptimizer.h:10,
                 from ../deps/v8/src/accessors.cc:9:
../deps/v8/src/string-stream.h: In member function 'void v8::internal::StringStream::Add(v8::internal::Vector<const char>, Args ...)':
../deps/v8/src/string-stream.h:130:34: error: no matching function for call to 'ArrayVector(v8::internal::StringStream::FmtElm [])'
     Add(format, ArrayVector(elems));
                                  ^
../deps/v8/src/string-stream.h:130:34: note: candidate is:
In file included from ../deps/v8/src/list.h:11:0,
                 from ../deps/v8/src/zone/zone.h:13,
                 from ../deps/v8/src/handles.h:15,
                 from ../deps/v8/src/accessors.h:11,
                 from ../deps/v8/src/accessors.cc:5:
../deps/v8/src/vector.h:212:18: note: template<class T, int N> v8::internal::Vector<T> v8::internal::ArrayVector(T (&)[N])
 inline Vector<T> ArrayVector(T (&arr)[N]) {
                  ^
../deps/v8/src/vector.h:212:18: note:   template argument deduction/substitution failed:
In file included from ../deps/v8/src/debug/debug.h:23:0,
                 from ../deps/v8/src/x64/assembler-x64-inl.h:11,
                 from ../deps/v8/src/assembler-inl.h:13,
                 from ../deps/v8/src/macro-assembler.h:8,
                 from ../deps/v8/src/deoptimizer.h:10,
                 from ../deps/v8/src/accessors.cc:9:
../deps/v8/src/string-stream.h:130:34: note:   mismatched types 'T [N]' and 'v8::internal::StringStream::FmtElm []'
     Add(format, ArrayVector(elems));
                                  ^
make[2]: *** [/home/iojs/build/workspace/node-test-commit-linux/nodes/ubuntu1204-64/out/Release/obj.target/v8_base/deps/v8/src/accessors.o] Error 1
```

BTW, Ubuntu 12.04 LTS will reach EOL in April 2017: https://www.ubuntu.com/info/release-end-of-life

**Comment by bnoordhuis** [comment]
With what gcc version is that?  The stock gcc is 4.6, IIRC, so we must be using a back-port of 4.8 or 4.9 if it worked before.

**Comment by targos** [comment]
Looking at the [ansible configuration](https://github.com/nodejs/build/blob/master/setup/ubuntu12.04/), it seems to be gcc-4.8. The PPA repository provides version [`4.8.4-1ubuntu15~12.04`](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=precise)

**Comment by targos** [comment]
Versions 4.9,4, 5.4.1 and 6.2.0 are all available in PPA. Maybe an upgrade is required?
/cc @nodejs/build

**Comment by bnoordhuis** [comment]
I would suggest either bumping the baseline to 4.8.5 or dropping support for 4.8 altogether, with a strong preference for the latter because the 4.8 release branch is abandoned.  4.8.4 was released more than two years ago, in 2014.

**Comment by rvagg** [comment]
Looks like we're now using 4.1 to compile on CentOS 5 (I missed that switch, not sure how long ago it was), leaving Ubuntu 12.04 as the old one. I suspect we'll run into further problems though when we do release builds with this because we're still using gcc 4.8 on Raspbian Wheezy for those on ARMv6 and we'll have to find a way to get that upgraded (not simple). Test builds are working because they cross-compile for speed. If we can find a solution to that then I'm OK with dropping 4.8. Any idea what version of gcc is minimum for this new version of V8?

**Comment by bnoordhuis** [comment]
I'm not sure.  V8's CI is built around clang, I think they have only a single gcc buildbot.  I don't know what version of gcc it uses but it's probably not 4.8.

**Comment by targos** [comment]
FWIW it works on CentOS 7 with this version: `(GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)`

**Comment by targos** [comment]
Related: https://github.com/nodejs/node/pull/11840

@rvagg: do you know what is the exact version on the rpi?

And for Ubuntu 12.04, I opened https://github.com/nodejs/build/pull/650 to upgrade gcc.

**Comment by mhdawson** [comment]
Have there been failures in your CI runs for ppc be or le  ?   They are at Ubuntu 14 and gcc reports as
4.8.4-2, maybe its just 4.8.4-2 that we need as the failing one you showed as 4.8.4-1

**Comment by targos** [comment]
Closing. The upgrade to 4.9 in https://github.com/nodejs/build/pull/650 fixed the issue.
@mhdawson maybe 4.8.4-2 would be enough but it isn't available for this version of Ubuntu
